kibot:
  version: 1

global:
  # variant: UnicraftAssembly
  filters:
  - number: 1007
  - number: 1015
  - number: 58
  - number: 107

import:
- file: JLCPCB
  definitions:
    _KIBOT_MANF_DIR: manufacturers/JLCPCB
    _KIBOT_POS_PRE_TRANSFORM: '[''_kicost_rename'', ''_rot_footprint'']'
    _KIBOT_BOM_ENABLED: 'false'
- file: PCBWay
  definitions:
    _KIBOT_MANF_DIR: manufacturers/PCBWay
- file: P-Ban
  definitions:
    _KIBOT_MANF_DIR: manufacturers/P-Ban

preflight:
  drc:
    dir: preflight/drc
    dont_stop: true
    format: HTML,RPT,JSON,CSV
  erc:
    dir: preflight/erc
    dont_stop: true
    format: HTML,RPT,JSON,CSV

outputs:
- name: bom
  type: bom
  dir: bom
  options:
    columns:
      # - "Row"
      # - "Part"
      - "Part Number"
      - "Quantity Per PCB"
      - "References"
      - "Value"
      # - "Footprint"
      - "Notes"
- name: schematic_pdf
  comment: Schematic PDF
  type: pdf_sch_print
  dir: pdf/schematic
- name: basic_pcb_print_pdf
  comment: PCB Layers PDF
  type: pcb_print
  dir: pdf/pcb
  options:
    format: PDF
    pages:
    - layers:
      - layer: F.Fab
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      sheet: Front documentation
    - layers:
      - layer: B.Fab
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      mirror: true
      sheet: Back documentation
    - layers:
      - layer: F.Cu
      - layer: F.Mask
        color: '#14332440'
      - layer: F.Paste
      - layer: F.Silkscreen
        color: '#f3f1cc'
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      sheet: Front copper
    # - layers:
    #   - layer: In1.Cu
    #   - layer: Edge.Cuts
    #   - layer: User.Drawings
    #   - layer: User.Comments
    #   sheet: 1st inner layer copper
    # - layers:
    #   - layer: In2.Cu
    #   - layer: Edge.Cuts
    #   - layer: User.Drawings
    #   - layer: User.Comments
    #   sheet: 2nd inner layer copper
    - layers:
      - layer: B.Cu
      - layer: B.Mask
        color: '#14332440'
      - layer: B.Paste
      - layer: B.Silkscreen
        color: '#f3f1cc'
      - layer: Edge.Cuts
      - layer: User.Drawings
      - layer: User.Comments
      mirror: true
      sheet: Back copper
    # - layers:
    #   - layer: F.Courtyard
    #   - layer: Edge.Cuts
    #   - layer: User.Drawings
    #   - layer: User.Comments
    #   sheet: Front courtyard area
    # - layers:
    #   - layer: B.Courtyard
    #   - layer: Edge.Cuts
    #   - layer: User.Drawings
    #   - layer: User.Comments
    #   mirror: false
    #   sheet: Back courtyard area
    keep_temporal_files: false
...
definitions:
  _KIBOT_MANF_DIR_COMP: manufacturers
  _KIBOT_GERBER_LAYERS:
    - layer: "Edge.Cuts"
      suffix: "Edge_Cuts"
      description: "Board shape"
    - layer: "F.Cu"
      suffix: "F_Cu"
      description: "Front copper"
    - layer: "B.Cu"
      suffix: "B_Cu"
      description: "Back copper"
    - layer: "F.SilkS"
      suffix: "F_SilkS"
      description: "Front silkscreen"
    - layer: "B.SilkS"
      suffix: "B_SilkS"
      description: "Back silkscreen"
    - layer: "F.Mask"
      suffix: "F_Mask"
      description: "Front solder mask"
    - layer: "B.Mask"
      suffix: "B_Mask"
      description: "Back solder mask"
    - layer: "In1.Cu"
      suffix: "In1_Cu"
      description: "Internal copper 1"
    - layer: "In2.Cu"
      suffix: "In2_Cu"
      description: "Internal copper 2"
    # - layer: "In3.Cu"
    #   suffix: "In3_Cu"
    #   description: "Internal copper 3"
    # - layer: "In4.Cu"
    #   suffix: "In4_Cu"
    #   description: "Internal copper 4"
    # - layer: "In5.Cu"
    #   suffix: "In5_Cu"
    #   description: "Internal copper 5"
    # - layer: "In6.Cu"
    #   suffix: "In6_Cu"
    #   description: "Internal copper 6"
